### ISSUE TITLE
Vagrantfile - box url 404 error

### ISSUE THREAD

**Issue by manugarri** [daeilkim/refinery#1]
I think the Vagrantfile needs to be updated with an updated box url. on line https://github.com/daeilkim/refinery/blob/master/Vagrantfile#L17

 I'm getting the following error when doing `vagrant up`:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'trusty64' (v0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/trusty64/version/1/provider/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found


```

**Comment by manugarri** [comment]
it would be a matter of replacing it with the link :

config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

**Comment by joaquinvanschoren** [comment]
This error still exists one year later. Will it be fixed soon?

**Comment by joaquinvanschoren** [comment]
@manugarri This fix works only partially. The 404 error is fixed but I get a different error now:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'trusty64' (v0) for provider: virtualbox
    default: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 60
```

**Comment by oolongtea** [comment]
This URL worked for me as of a few minutes ago, so I changed the line in the `Vagrantfile` to this:

`config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"`

I still got an Internal Server Error once I went to http://11.11.11.11:8080 but at least the download worked. Server error may be related to https://github.com/daeilkim/refinery/issues/5.

Edit: The fix I provided at https://github.com/daeilkim/refinery/issues/5 worked for me; I got to the login screen.

**Comment by daeilkim** [comment]
Fixed the url in the newest push. Thanks for finding that error!
